import Sidebar from "@/components/Sidebar";
import Head from "next/head";
import Image from "next/image";

const Financials = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="main-container">
          <Sidebar />
          <div className="main-content">
            <div className="home-top-panel-out">
              <div className="home-top-panel">
                <h2>Dashboard</h2>
                <input type="text" placeholder="🔎︎ Search here..." />
                <select className="select-language">
                  <option value="eng">Eng (US)</option>
                  <option value="eng">Eng (US)</option>
                </select>
                <div className="travis-card">
                  <Image
                    src="/image/travis.png"
                    alt="travis_image"
                    height={54}
                    width={55}
                    className="travis_image"
                  />
                  <p>Travis Herron</p>
                </div>
              </div>
            </div>
            <div className="container">
              <div className="table">
                <div className="table-head">
                  <p className="financial-amount">Aggregates Amounts</p>
                  <p className="financial-revenue">Revenue</p>
                  <p className="financial-assets">Assets</p>
                  <p className="financial-profit">Profit</p>
                  <p className="financial-acqCost">Customer Acquistion Cost</p>
                  <p className="financial-costCustomer">Cost Per Customer</p>
                  <p className="financial-projection">Projections</p>
                </div>
                <div className="table-body">
                  <p className="financial-amount">40$</p>
                  <p className="financial-revenue">40%</p>
                  <p className="financial-assets">3</p>
                  <p className="financial-profit">40$</p>
                  <p className="financial-acqCost">40$</p>
                  <p className="financial-costCustomer">40$</p>
                  <p className="financial-projection">40%</p>
                </div>
                <div className="table-body">
                  <p className="financial-amount">40$</p>
                  <p className="financial-revenue">40%</p>
                  <p className="financial-assets">3</p>
                  <p className="financial-profit">40$</p>
                  <p className="financial-acqCost">40$</p>
                  <p className="financial-costCustomer">40$</p>
                  <p className="financial-projection">40%</p>
                </div>
                <div className="table-body">
                  <p className="financial-amount">40$</p>
                  <p className="financial-revenue">40%</p>
                  <p className="financial-assets">3</p>
                  <p className="financial-profit">40$</p>
                  <p className="financial-acqCost">40$</p>
                  <p className="financial-costCustomer">40$</p>
                  <p className="financial-projection">40%</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  );
};

export default Financials;
