import Sidebar from "@/components/Sidebar";
import Head from "next/head";
import Image from "next/image";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="main-container">
          <Sidebar />
          <div className="main-content">
            <div className="container">
              <div className="home-top-panel">
                <h2>Dashboard</h2>
                <input type="text" placeholder="🔎︎ Search here..." />
                <select className="select-language">
                  <option value="eng">Eng (US)</option>
                  <option value="eng">Eng (US)</option>
                </select>
                <div className="travis-card">
                  <Image
                    src="/image/travis.png"
                    alt="travis_image"
                    height={54}
                    width={55}
                    className="travis_image"
                  />
                  <p>Travis Herron</p>
                </div>
              </div>
              <div className="home-overview-panel">
                <p className="overview">
                  <b>Monthly</b>
                  <br />
                  Overview
                </p>
                <p className="revenue">
                  Monthly Revenue
                  <br />
                  <b>$14,000</b>
                </p>
                <p className="plus">+</p>
                <p className="expenses">
                  Monthly Expenses
                  <br />
                  <b>-$4,000</b>
                </p>
                <p className="equal">=</p>
                <p className="profit">
                  Monthly Profit
                  <br />
                  <b>$10,000</b>
                </p>
                <p className="top">
                  Tap #
                  <br />
                  <b>5,000</b>
                </p>
              </div>
              <div className="home-overview-bottom-panel">
                <div className="overview-card">
                  <Image
                    src="/image/revenueicon.png"
                    alt="revenueicon"
                    height={40}
                    width={40}
                    className="top-overview-card"
                  />
                  <h4>$14,000</h4>
                  <p>Product Revenue</p>
                  <span>+</span>
                </div>
                <div className="overview-card">
                  <Image
                    src="/image/gasicon.png"
                    alt="gasicon"
                    height={40}
                    width={40}
                    className="top-overview-card"
                  />
                  <h4>1004</h4>
                  <p>Gas Subsidy Request</p>
                  <span>+</span>
                </div>
                <div className="overview-card">
                  <Image
                    src="/image/supporticon.png"
                    alt="supporticon"
                    height={40}
                    width={40}
                    className="top-overview-card"
                  />
                  <h4>112</h4>
                  <p>Support request</p>
                  <span>+</span>
                </div>
                <div className="overview-card">
                  <Image
                    src="/image/refferalicon.png"
                    alt="refferalicon"
                    height={40}
                    width={40}
                    className="top-overview-card"
                  />
                  <h4>456</h4>
                  <p>Refferal Payouts</p>
                  <span>+</span>
                </div>
                <div className="overview-card">
                  <Image
                    src="/image/unfulfillicon.png"
                    alt="unfulfillicon"
                    height={40}
                    width={40}
                    className="top-overview-card"
                  />
                  <h4>3245</h4>
                  <p>Unfulfilled Orders</p>
                  <span>+</span>
                </div>
                <div className="overview-card">
                  <Image
                    src="/image/subscribericon.png"
                    alt="subscribericon"
                    height={40}
                    width={40}
                    className="top-overview-card"
                  />
                  <h4>564</h4>
                  <p>Subscribers</p>
                  <span>+</span>
                </div>
                <div className="overview-card">
                  <Image
                    src="/image/micrositesicon.png"
                    alt="micrositesicon"
                    height={40}
                    width={40}
                    className="top-overview-card"
                  />
                  <h4>435</h4>
                  <p>Microsites</p>
                  <span>+</span>
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
