import Sidebar from "@/components/Sidebar";
import Head from "next/head";
import Image from "next/image";
import { BiDownload } from "react-icons/bi";
import { HiOutlineEye } from "react-icons/hi";

const Cupons = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="main-container">
          <Sidebar />
          <div className="main-content">
            <div className="home-top-panel-out">
              <div className="home-top-panel">
                <h2>Dashboard</h2>
                <input type="text" placeholder="🔎︎ Search here..." />
                <select className="select-language">
                  <option value="eng">Eng (US)</option>
                  <option value="eng">Eng (US)</option>
                </select>
                <div className="travis-card">
                  <Image
                    src="/image/travis.png"
                    alt="travis_image"
                    height={54}
                    width={55}
                    className="travis_image"
                  />
                  <p>Travis Herron</p>
                </div>
              </div>
            </div>
            <div className="container">
              <div className="filter">
                <p>Filter</p>
                <select>
                  <option>Date</option>
                </select>
                <select>
                  <option>Name</option>
                </select>
                <button type="submit">
                  Export <BiDownload size={20} />
                </button>
              </div>
              <div className="table">
                <div className="table-head">
                  <p className="cupon-cupon">Cupon</p>
                  <p className="cupon-name">Name</p>
                  <p className="cupon-promocode">Promocode</p>
                  <p className="cupon-amount">Amount</p>
                  <p className="cupon-minAmount">Minimum Amount</p>
                  <p className="cupon-exDate">Expire Date</p>
                  <p className="cupon-view">View</p>
                </div>
                <div className="table-body">
                  <p className="cupon-cupon">
                    <Image
                      src="/image/cupon.png"
                      alt="cupon_image"
                      height={93}
                      width={52}
                    />
                  </p>
                  <div className="cupon-name table-image">
                    <Image
                      src="/image/supportImage.png"
                      alt="user_image"
                      height={45}
                      width={45}
                    />
                    <p>Hamid Hasan</p>
                  </div>
                  <p className="cupon-promocode">8hg4xcvv</p>
                  <p className="cupon-amount">$80</p>
                  <p className="cupon-minAmount">$50</p>
                  <p className="cupon-exDate">7/11/2022</p>
                  <p className="cupon-view">
                    <HiOutlineEye size={20} color={"#5197ca"} />
                  </p>
                </div>
                <div className="table-body">
                  <p className="cupon-cupon">
                    <Image
                      src="/image/cupon.png"
                      alt="cupon_image"
                      height={93}
                      width={52}
                    />
                  </p>
                  <div className="cupon-name table-image">
                    <Image
                      src="/image/supportImage.png"
                      alt="user_image"
                      height={45}
                      width={45}
                    />
                    <p>Hamid Hasan</p>
                  </div>
                  <p className="cupon-promocode">8hg4xcvv</p>
                  <p className="cupon-amount">$80</p>
                  <p className="cupon-minAmount">$50</p>
                  <p className="cupon-exDate">7/11/2022</p>
                  <p className="cupon-view">
                    <HiOutlineEye size={20} color={"#5197ca"} />
                  </p>
                </div>
                <div className="table-body">
                  <p className="cupon-cupon">
                    <Image
                      src="/image/cupon.png"
                      alt="cupon_image"
                      height={93}
                      width={52}
                    />
                  </p>
                  <div className="cupon-name table-image">
                    <Image
                      src="/image/supportImage.png"
                      alt="user_image"
                      height={45}
                      width={45}
                    />
                    <p>Hamid Hasan</p>
                  </div>
                  <p className="cupon-promocode">8hg4xcvv</p>
                  <p className="cupon-amount">$80</p>
                  <p className="cupon-minAmount">$50</p>
                  <p className="cupon-exDate">7/11/2022</p>
                  <p className="cupon-view">
                    <HiOutlineEye size={20} color={"#5197ca"} />
                  </p>
                </div>
                <div className="table-body">
                  <p className="cupon-cupon">
                    <Image
                      src="/image/cupon.png"
                      alt="cupon_image"
                      height={93}
                      width={52}
                    />
                  </p>
                  <div className="cupon-name table-image">
                    <Image
                      src="/image/supportImage.png"
                      alt="user_image"
                      height={45}
                      width={45}
                    />
                    <p>Hamid Hasan</p>
                  </div>
                  <p className="cupon-promocode">8hg4xcvv</p>
                  <p className="cupon-amount">$80</p>
                  <p className="cupon-minAmount">$50</p>
                  <p className="cupon-exDate">7/11/2022</p>
                  <p className="cupon-view">
                    <HiOutlineEye size={20} color={"#5197ca"} />
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  );
};

export default Cupons;
