import Sidebar from "@/components/Sidebar";
import Head from "next/head";
import Image from "next/image";

const Orders = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="main-container">
          <Sidebar />
          <div className="main-content">
            <div className="home-top-panel-out">
              <div className="home-top-panel">
                <h2>Dashboard</h2>
                <input type="text" placeholder="🔎︎ Search here..." />
                <select className="select-language">
                  <option value="eng">Eng (US)</option>
                  <option value="eng">Eng (US)</option>
                </select>
                <div className="travis-card">
                  <Image
                    src="/image/travis.png"
                    alt="travis_image"
                    height={54}
                    width={55}
                    className="travis_image"
                  />
                  <p>Travis Herron</p>
                </div>
              </div>
            </div>
            <div className="container">
              <div className="filter">
                <p>Filter</p>
                <select>
                  <option>Date</option>
                </select>
                <select>
                  <option>Name</option>
                </select>
              </div>
              <div className="table">
                <div className="table-head">
                  <p className="order-no">Order No</p>
                  <p className="order-customer">Customer</p>
                  <p className="order-product">Product</p>
                  <p className="order-price">Price</p>
                  <p className="order-date">Delivery Date</p>
                  <p className="order-status">Delivery Status</p>
                </div>
                <div className="table-body">
                  <p className="order-no">1009701</p>
                  <div className="order-customer table-image">
                    <Image
                      src="/image/supportImage.png"
                      alt="user_image"
                      height={45}
                      width={45}
                    />
                    <p>Hamid Hasan</p>
                  </div>
                  <p className="order-product">Black NFC Card</p>
                  <p className="order-price">$24.99</p>
                  <p className="order-date">7/11/2022</p>
                  <p className="order-status">
                    <span style={{ backgroundColor: "#ffa800" }}>
                      Processing
                    </span>
                  </p>
                </div>
                <div className="table-body">
                  <p className="order-no">1009701</p>
                  <div className="order-customer table-image">
                    <Image
                      src="/image/supportImage.png"
                      alt="user_image"
                      height={45}
                      width={45}
                    />
                    <p>Hamid Hasan</p>
                  </div>
                  <p className="order-product">Black NFC Card</p>
                  <p className="order-price">$24.99</p>
                  <p className="order-date">7/11/2022</p>
                  <p className="order-status">
                    <span style={{ backgroundColor: "#2ac53a" }}>Complete</span>
                  </p>
                </div>
                <div className="table-body">
                  <p className="order-no">1009701</p>
                  <div className="order-customer table-image">
                    <Image
                      src="/image/supportImage.png"
                      alt="user_image"
                      height={45}
                      width={45}
                    />
                    <p>Hamid Hasan</p>
                  </div>
                  <p className="order-product">Black NFC Card</p>
                  <p className="order-price">$24.99</p>
                  <p className="order-date">7/11/2022</p>
                  <p className="order-status">
                    <span style={{ backgroundColor: "#ff4f4f" }}>Cancel</span>
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  );
};

export default Orders;
